[package]
name = "transaction-log-exports"
version.workspace = true
edition.workspace = true

[dependencies]
bytes.workspace = true
crc32c.workspace = true
getset.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }

[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true
tempfile = "3"
tokio = { workspace = true, features = ["net", "time"] }

[[bench]]
name = "record_reader"
harness = false
test = false

[[bench]]
name = "record_writer"
harness = false
test = false

[[bench]]
name = "record_io"
harness = false
test = false
